// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA8iSQH-LEnvj14lGK4pfYxIVr5t7cgVo',
    appId: '1:117042467856:android:f1554cd5e0db32d9a4a695',
    messagingSenderId: '117042467856',
    projectId: 'booking-app-2024',
    storageBucket: 'booking-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCepxdTStmpCzOi5O3x-3EnH613BpmtQcA',
    appId: '1:117042467856:ios:46ffbc9a502f6bfea4a695',
    messagingSenderId: '117042467856',
    projectId: 'booking-app-2024',
    storageBucket: 'booking-app-2024.appspot.com',
    androidClientId: '117042467856-0jbfl520jhp9qk4s99mi5g4kde0dqo0u.apps.googleusercontent.com',
    iosClientId: '117042467856-qml4g1ur3e83nbtoms91vrit5g4i5fi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingAppR1',
  );
}
